# Configuracoes do Servidor
server.port=8082
spring.application.name=product-service

# Configuracoes do H2 Database
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Configuracoes do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Console H2 (para debug)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs
logging.level.com.example.productservice=DEBUG